trigger:
  branches:
    include:
      - main

parameters:
  - name: dev_username
    displayName: 'Developer Username'
    type: string
    default: 'johndoe'

variables:
  TF_VAR_resource_group_name: 'secure-dev-env-rg'
  TF_VAR_location: 'East US'
  TF_VAR_dev_username: ${{ parameters.dev_username }}

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Request
  displayName: 'Request Approval'
  jobs:
  - deployment: RequestApproval
    displayName: 'Await Manual Approval'
    environment: 'DevEnv-Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Please approve to provision a secure dev environment for ${{ parameters.dev_username }}.'
              onTimeout: 'reject'
              timeout: '1h'

- stage: Deploy
  displayName: 'Deploy Infrastructure'
  dependsOn: Request
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Deployment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login --identity
        az account set --subscription "<SUBSCRIPTION_ID>"
      displayName: 'Azure Login with Managed Identity'

    - script: |
        terraform init
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Plan & Apply'